name: Publish to npm

on:
  push:
    branches:
      - main       # 监听 main 分支的推送
    tags:
      - 'v*'       # 监听以 v 开头的 tag（如 v1.0.0）

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 指定 Node.js 版本
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci          # 使用精确的依赖安装

      - name: img-hotspot
        run: npm run build  # 生成构建产物（如 dist/ 目录）

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # 上传构建产物（可选）
          files: |
            dist/*.js
            README.md
            package.json
          # 自动生成 Release 说明（基于提交记录）
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token

          